planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/ValidateWorkspaceBounds
  default_planner_request_adapters/CheckStartStateBounds
  default_planner_request_adapters/CheckStartStateCollision
  default_planner_request_adapters/AddTimeOptimalParameterization
start_state_max_bounds_error: 0.10

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1

hand:
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
  longest_valid_segment_fraction: 0.01
