FROM ros:humble-ros-base-jammy

ARG DEBIAN_FRONTEND=noninteractive
ARG ROARM_VENDOR_COMMIT=40dbd84b553695212fab713e8465f817ba95454d

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libgl1-mesa-dri \
    mesa-utils \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    python3-serial \
    python3-vcstool \
    ros-humble-joint-state-publisher \
    ros-humble-moveit \
    ros-humble-robot-state-publisher \
    ros-humble-rviz2 \
    ros-humble-xacro \
    xauth \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/roarm_vendor_ws/src && \
    git clone --filter=blob:none --no-checkout \
      https://github.com/waveshareteam/roarm_ws.git \
      /opt/roarm_vendor_ws/src/roarm_ws && \
    git -C /opt/roarm_vendor_ws/src/roarm_ws sparse-checkout init --cone && \
    git -C /opt/roarm_vendor_ws/src/roarm_ws sparse-checkout set \
      src/roarm_main/roarm_description \
      src/roarm_main/roarm_moveit \
      src/roarm_main/roarm_moveit_ikfast_plugins && \
    git -C /opt/roarm_vendor_ws/src/roarm_ws checkout "${ROARM_VENDOR_COMMIT}" && \
    /bin/bash -lc 'source /opt/ros/humble/setup.bash && \
      cd /opt/roarm_vendor_ws && \
      colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --packages-select roarm_description roarm_moveit roarm_moveit_ikfast_plugins' && \
    rm -rf /opt/roarm_vendor_ws/build /opt/roarm_vendor_ws/log

WORKDIR /workspace/src/ros2_ws
COPY docker/ros2_entrypoint.sh /ros2_entrypoint.sh
RUN chmod +x /ros2_entrypoint.sh
ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["/bin/bash"]
