<?xml version="1.0"?>
<package format="3">
  <name>eee8097_moveit_config</name>
  <version>0.3.0</version>
  <description>Arm-only MoveIt 2 configuration for the EEE8097 RoArm-M2-S.</description>
  <maintainer email="117880292+lester-zed@users.noreply.github.com">lester-zed</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>eee8097_moveit_bridge</exec_depend>
  <exec_depend>eee8097_roarm_driver</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>roarm_description</exec_depend>
  <exec_depend>roarm_moveit</exec_depend>
  <exec_depend>roarm_moveit_ikfast_plugins</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
